marketcalls/openalgo

blueprints/search.py
database/master_contract_db.py
templates/token.html

modified:   database/master_contract_db.py
modified:   templates/token.html

	modified:   blueprints/search.py

---

blueprints/orders.py
broker/fyers/api/order_api.py
broker/fyers/database/master_contract_db.py
broker/fyers/mapping/order_data.py
utils/auth_utils.py

Bug Fixes to Fyers Master Contract Download

Multibroker

---

README.md
blueprints/brlogin.py
broker/dhan/api/auth_api.py
broker/dhan/api/funds.py
broker/dhan/api/order_api.py
broker/dhan/database/master_contract_db.py
broker/dhan/mapping/order_data.py
broker/dhan/mapping/transform_data.py
templates/broker.html

Dhan Integration with OpenAlgo

Dhan Integration with OpenAlgo

---

.sample.env
blueprints/core.py
blueprints/log.py
templates/components/loading_spinner.html
templates/components/log_entry.html
templates/components/logs_filters.html
templates/components/logs_scripts.html
templates/components/logs_styles.html
templates/components/pagination.html
templates/download.html
templates/faq.html
templates/index.html
templates/logs.html

Enhanced Log Functionality. Making the Boring logs interesting
OpenAlgo's Trading Logs Interface! Here's what we built:
Enhanced Visualization:
Modern card-based design with smooth hover animations
Color-coded badges for different API types (placeorder, modifyorder, etc.)
Visual indicators for BUY/SELL actions with intuitive icons
Quick-view panels for essential order details
Custom gradient badges for strategy and exchange information
Advanced Filtering & Search:
Real-time search functionality with debouncing
Date range filtering with intuitive calendar inputs
Smart pagination for handling large datasets
Instant filtering without page reloads
Modern UI/UX Features:
Responsive design that works beautifully on all devices
Collapsible JSON data sections for cleaner viewing
Loading states …

Log enhancement and Added FAQ Page

---

static/js/socket-events.js

Fixing the theStats Update of Orderbook and TradeBook on socket event

Updating the Stats of Orderbook and TradeBook on socket event

---

static/js/socket-events.js
templates/orderbook.html
templates/positions.html
templates/tradebook.html
utils/api_analyzer.py

updating API Log Analyzer doubble logging fix

updating API Log Analyzer doubble logging fix

---

database/user_db.py

user_db findbyusername error fix

---

database/user_db.py

updated find user by username function

---

broker/fyers/api/data.py
data.md
requirements-nginx.txt
requirements.txt
restx_api/__init__.py
restx_api/account_schema.py
restx_api/basket_order.py
restx_api/data_schemas.py
restx_api/depth.py
restx_api/funds.py
restx_api/history.py
restx_api/holdings.py
restx_api/intervals.py
restx_api/openposition.py
restx_api/orderbook.py
restx_api/orderstatus.py
restx_api/positionbook.py
restx_api/quotes.py
restx_api/schemas.py
restx_api/split_order.py
restx_api/tradebook.py
static/js/socket-events.js
strategies/data_history_test.py
strategies/ema_crossover.py
strategies/supertrend.py
utils/version.py

Updated the Following API's
Account API
-Funds
-OrderBook
-TradeBook
-PositionBook
-Holdings
OrderAPI
-BasketOrder
-SplitOrder
-OrderStatus
-OpenPosition
DataApi(Pilot with Fyers)
-quote
-depth
-history
-interval
Added Sample Strategies under Strategies Folder (Supertrend and Simple EMA Crossover) which works with newer history data api. (Currently supports only fyers as part of pilot implementation and other brokers soon it will get implemented)

Newer API's

---

INSTALL.md
README.md
broker/icici/database/master_contract_db.py
package-lock.json
package.json
postcss.config.js
src/css/styles.css
static/css/main.css
static/css/prism.css
static/js/mode-toggle.js
static/js/theme.js
tailwind.config.js
templates/base.html
templates/layout.html
templates/search.html
utils/version.py

Local Compilation of TailWind and Daisy UI 
Added Install.md Document
ICICIDirect  NAN values in Symbols Fix

Local Compilation of TailWind and Daisy UI and ICICIDirect  NAN values in Symbols Fix

---

package.json
postcss.config.js
tailwind.config.js

update the tailwind and daisyUI config

update the tailwind and daisyUI config

---

restx_api/place_order.py
restx_api/place_smart_order.py

supporting buy and sell lower case in RESTX API in PlaceOrder and PlaceSmartOrder

supporting buy and sell lower case in RESTX API

---

app.py
broker/fyers/database/master_contract_db.py
utils/config.py
utils/env_check.py

Centralized ENV Check with override

Centralized ENV Check with override

---

.sample.env
Dockerfile
app.py
static/js/app.js
static/js/mode-toggle.js
static/js/socket-events.js
static/js/tradingview.js
templates/5paisa.html
templates/aliceblue.html
templates/angel.html
templates/apikey.html
templates/base.html
templates/broker.html
templates/chartink/configure_symbols.html
templates/chartink/index.html
templates/chartink/view_strategy.html
templates/components/logs_scripts.html
templates/index.html
templates/kotak.html
templates/kotakotp.html
templates/latency/dashboard.html
templates/login.html
templates/navbar.html
templates/public_navbar.html
templates/shoonya.html
templates/token.html
templates/tradingview.html
templates/traffic/dashboard.html
templates/zebu.html

Make application aware about reverse proxy
Tested
* Broker login
* Tradingview page
* API key generation
*

Application root changes

---

broker/flattrade/api/funds.py
broker/shoonya/api/funds.py
broker/zebu/api/funds.py

Realized P&L fix for kambala (shoonya, flattrade, zebu) brokers - fixed funds.py

Realized P&L fix for kambala (shoonya, flattrade, zebu) brokers 

---

templates/dashboard.html

Dashboard Error Fix if the user changes the apikey and api secret to handle the invalid login gracefully.

Dashboard Error Fix 

---

broker/angel/api/data.py
broker/fyers/api/data.py
restx_api/depth.py
restx_api/history.py
restx_api/holdings.py
restx_api/intervals.py
restx_api/quotes.py

Added AngelAPI and removed the Hardcoded Class FyersData and renamed to BrokerData

Added AngelAPI 

---

broker/upstox/api/data.py

Upstox Data API implementation done

Upstox Data API

---

broker/flattrade/database/master_contract_db.py
broker/shoonya/api/data.py

shoonya data api addition

---

broker/angel/api/data.py
broker/zebu/api/data.py
restx_api/intervals.py

Zebu api update and minor Shoonya and Angel Data API fix. Removing the…hardcoding of D,W,M timeframe from RESTX API

Zebu data api update 

---

broker/flattrade/api/data.py

FlatTrade Data API Implementation

FlatTrade Data API Implementation

---

broker/icici/api/data.py

ICICI Direct Data API Fix

---

restx_api/place_smart_order.py

fixing log write once the order is sent for placesmartorder
I've published a new release that addresses the logging timestamp issue. Here are the key changes:
1. **Fixed Order Logging Sequence**
- Order logs are now written immediately after order placement
- Timestamps in logs now accurately reflect when orders were sent to the broker
- The configured delay (SMART_ORDER_DELAY) no longer affects the logged timestamp
2. **Clarification on Delays**
The smart order process has two types of delays:
- Position check delay (before order placement) - Required API call to check current positions
- Configured SMART_ORDER_DELAY (after order placement) - Configurable rate limiting
3. **More Accurate Timestamps**
- Previous: Timestamps included both position check and configured delays
- Now: …

fixing log write once the order is sent

---

broker/dhan/api/funds.py
broker/dhan/api/order_api.py
broker/dhan/mapping/transform_data.py
restx_api/holdings.py

Upgraded Dhan OpenAlgo Integration with V2 Version
https://dhanhq.co/docs/v2/
Fixed the Holdings RestX API
Used the imported broker_funcs dictionary to call the get_holdings function directly with the auth token

Dhan Upgrade to V2 API Version

---

broker/dhan/api/data.py

Dhan Data API Integration

---

broker/upstox/api/data.py

fixing upstox timezone issue Properly handling timezone-aware datetimes by removing the timezone information before conversion

fixing upstox timezone issue 

---

docs/ticker.md
restx_api/__init__.py
restx_api/data_schemas.py
restx_api/ticker.py

Amiquote Ticker Update sends EOD and 1min Data to Amibroker

Amiquote Ticker Update

---

blueprints/brlogin.py
broker/kotak/api/auth_api.py
broker/kotak/api/funds.py
broker/kotak/api/order_api.py
broker/kotak/mapping/order_data.py
templates/kotak.html
templates/kotakotp.html

I have updated the kotak to login using only `consumer_key` & `consumer_secret` without generating the `access_token` on the kotak api dashboard.
API endpoint with proper headers & query's.
Fixed the `ZeroDivisionError: float division by zero` on holding page.
Fixed the negative `Unrealized` & `Realized P&L` on dashboard.

Updated Kotak Login Flow & Bug Fix

---

blueprints/brlogin.py
broker/kotak/api/auth_api.py
broker/kotak/api/funds.py
broker/kotak/api/order_api.py
broker/kotak/mapping/order_data.py
templates/kotak.html
templates/kotakotp.html

Reverts marketcalls/openalgo#141

Revert "Updated Kotak Login Flow & Bug Fix"

---

broker/firstock/api/data.py

Firstockdata Data API

---

broker/firstock/api/data.py

firstock updated fix for special symbols

updated fix for special symbols

---

app.py
blueprints/core.py
blueprints/strategy.py
database/strategy_db.py
docs/strategy.md
static/css/main.css
templates/apikey.html
templates/base.html
templates/chartink/view_strategy.html
templates/navbar.html
templates/strategy/configure_symbols.html
templates/strategy/index.html
templates/strategy/new_strategy.html
templates/strategy/view_strategy.html
utils/version.py

- Provided Basic Strategy Management Module for Amibroker, Tradingview, Python, Excel, Metatrader 
etc with timing controls and auto squareoff
- Documentation of Strategy Management Module under /docs folder
- Auto Generation of API Keys at the Registration
-  Moved Holdings from Top Navigation Bar to Profile Flyout Menu

Basic Strategy Management Module

---

blueprints/brlogin.py
broker/kotak/api/HSWebSocketLib.py
broker/kotak/api/auth_api.py
broker/kotak/api/data.py
broker/kotak/api/funds.py
broker/kotak/api/order_api.py
broker/kotak/database/master_contract_db.py
broker/kotak/mapping/order_data.py
static/css/main.css
templates/kotak.html
templates/kotakotp.html

I have updated the kotak to login using only `consumer_key` & `consumer_secret` without generating the `access_token` on the kotak api dashboard.
API endpoint with proper headers & query's.
Fixed the `ZeroDivisionError: float division by zero` on holding page.
Fixed the negative `Unrealized` & `Realized P&L` on dashboard.
Fixed the masterscript invalid auth token.

Updated Kotak Login Flow & Bug Fix, Data API

---

broker/flattrade/api/funds.py

Released margin and unreleased margin calculation are done using position api.

flatTrade P&L fix

---

broker/angel/api/data.py
broker/jainampro/api/auth_api.py
broker/jainampro/baseurl.py

Angel Historic Data Fetch Fixed

Angel Historic Data Fetch Fixed

---

.gitignore
blueprints/brlogin.py
broker/pocketful/api/auth_api.py
broker/pocketful/api/funds.py
broker/pocketful/database/master_contract_db.py
broker/pocketful/plugin.json
templates/broker.html

Pocketful broker integration - Authentication Flow, funds and Master Contract update

Pocketful broker integration - Authentication Flow, funds and Master Contract update

---

broker/fivepaisa/database/master_contract_db.py

master_contract_db update for fivepaisa update

master_contract_db update for fivepaisa 

---

broker/fivepaisa/api/data.py
broker/fivepaisa/api/order_api.py
broker/fivepaisa/database/master_contract_db.py
broker/fivepaisa/mapping/order_data.py
broker/fivepaisa/mapping/transform_data.py

Fivepaisa Order API s Update - Common index symbols, cancel,modify,cancelall orders and close positions update

Fivepaisa Order API s Update

---

blueprints/brlogin.py
broker/aliceblue/api/alicebluewebsocket.py
broker/aliceblue/api/auth_api.py
broker/aliceblue/api/data.py
broker/aliceblue/api/funds.py
broker/aliceblue/api/order_api.py
broker/aliceblue/database/master_contract_db.py

Aliceblue shared connection pooling and data handling update

Aliceblue shared connection pooling and data handling update

---

websocket_proxy/base_adapter.py

ZMQ port configuration in dotenv file fixed

ZMQ port configuration in dotenv file fixed

---

broker/dhan/streaming/__init__.py
broker/dhan/streaming/dhan_adapter.py
broker/dhan/streaming/dhan_mapping.py
broker/dhan/streaming/dhan_websocket.py
test/iteration_test.py
websocket_proxy/__init__.py
websocket_proxy/server.py

websocket dictionary Iteration Fix

websocket dictionary Iteration Fix

---

utils/httpx_client.py

This will automatically switch from http2 to http1 if it fails.

Automatically Switch Between http2/1

---

broker/angel/api/data.py
broker/angel/streaming/angel_adapter.py
broker/dhan/streaming/dhan_websocket.py
restx_api/data_schemas.py
restx_api/history.py
services/history_service.py

Dhan 20 level token mapping , Open Interest field inclusion in history as well OI included in quotes,history and websocket snapquote

Dhan 20 level token mapping and Open Interest field inclusion in history 

---

broker/angel/api/data.py
broker/angel/streaming/angel_adapter.py
broker/zerodha/api/data.py
restx_api/data_schemas.py
restx_api/history.py
services/history_service.py

Removal of include_oi parameter and OI addition in angel and zerodha's quote and history

Removal of include_oi parameter and OI addition in angel and zerodha's quote and history

---

.sample.env
README.md
broker/compositedge/streaming/__init__.py
broker/compositedge/streaming/compositedge_adapter.py
broker/compositedge/streaming/compositedge_mapping.py
broker/compositedge/streaming/compositedge_websocket.py
install/install.sh
templates/faq.html
websocket_proxy/__init__.py

Ibulls added in the .sample.env ,install.sh,faq.html and README.md and Compositedge Websocket Integration's - Initial Commit

Ibulls added in .sample.env ,install.sh and Compositedge Websocket Integration

---

websocket_proxy/base_adapter.py

- **Added**: Socket options configuration in `_create_socket()` method
- **Benefit**: Better socket performance and resource management
```python
socket.setsockopt(zmq.LINGER, 1000)  # 1 second linger
socket.setsockopt(zmq.SNDHWM, 1000)  # High water mark
```
- **Added**: Shared context management across instances with `_initialize_shared_context()`
- **Added**: Class variables: `_shared_context`, `_context_lock` 
- **Benefit**: Better resource utilization and prevents context conflicts
```python
self.context = zmq.Context()
def _initialize_shared_context(self):
with self._context_lock:
if not BaseBrokerWebSocketAdapter._shared_context:
BaseBrokerWebSocketAdapter._shared_context = zmq.Context()
```
- **Improved**: `find_free_zmq_port()` function with cleaner port registry cleanup
- …

fix port binding conflict

---

broker/groww/api/auth_api.py

Groww Auth using API Key and Secret Updated

Groww Auth using API Key and Secret Updated

---

broker/upstox/api/order_api.py

Upstox- place order response Fixed. tested other order apis also

Upstox- place order response Fixed
